### ISSUE TITLE
There appears to be no root dialog - bot crashes with Error: Dialog[*:/] not found

### ISSUE THREAD

**Issue by nwhitmont** [richdizz/microsoft-graph-sentiment-bot#2]
I tried to run the bot, but as soon as I send a message to the bot via emulator, the bot immediately crashes with error:
```
ChatConnector: message received.
UniversalBot("*") routing "hi" from "emulator"
Session.beginDialog(/)
Error: Dialog[*:/] not found.
```

![screen shot 2017-06-21 at 2 58 42 pm](https://user-images.githubusercontent.com/3075047/27408624-76cc6378-5692-11e7-851b-5a80b65c8ae5.png)

Relates to: https://stackoverflow.com/questions/44683074/bot-framework-error

**Comment by richdizz** [comment]
I have added a default dialog to the project.

**Comment by nwhitmont** [comment]
thanks
